### ISSUE TITLE
using rxfirebase in android things/enum/kotlin project

### ISSUE THREAD

**Issue by neuberfran** [davidvavra/mobcon-sample-code#1]
https://stackoverflow.com/questions/52639350/kotlin-enum-class-with-companion-object-integrate-with-field-of-the-firebase-dat

Hi, 

I need your help to integrate rxfirebase in my project

Do You have used rxfirebase2 or rxfirebase1?

**Comment by davidvavra** [comment]
Sorry, this library is not StackOverflow

**Comment by neuberfran** [comment]
@davidvavra You did not understand my question. I have a issue in my android things project using enum and firebase without Rx, look link above of the stackoverflow. How to rxfirebase will help me? Do you use rxfirebase1 or rxfirebase2? pls help me
